
(function(){var settings={'max_undo':20,'undoChange':function(){},'redoChange':function(){}};var UndoManager=function(set){this.action_index={};this.next_id=1;this.undo_queue=[];this.redo_queue=[];this.current_action=null;this.group=null;this.group_queue=[];this.group_id=0;this.working='';this.undo_available=0;this.undo_names=[];this.redo_available=0;this.redo_names=[];this.changeSettings(set);};UndoManager.prototype.changeSettings=function(set){this.settings=settings;for(attrname in set){if(set.hasOwnProperty(attrname)){this.settings[attrname]=set[attrname];}}
this.settings=$.extend(settings,set);};UndoManager.prototype.groupRunner=function(actions){var id;while((id=actions.pop())){var action=this.action_index[id];delete this.action_index[id];action[1].apply(action[3],action[2]);}};UndoManager.prototype.undoable=function(name,func,parameters,context,id,add_to_queue_overwrite){if(this.group!==null){id=id||this.next_id++;this.action_index[id]=[name,func,parameters,context];this.group[2][0].push(id);return this;}
var queue=this.undo_queue;if(this.working=='UNDO'){queue=this.redo_queue;}
id=id||this.next_id++;this.action_index[id]=[name,func,parameters,context];if(!add_to_queue_overwrite){queue.push(id);if(queue.length>this.settings.max_undo){queue.shift();if(this.working=='UNDO'){this.redo_available--;this.redo_names.shift();}else{this.undo_available--;this.undo_names.shift();}}
if(this.working=='UNDO'){this.redo_available++;this.redo_names.push(this.current_action[0]);this.settings.redoChange();}else{this.undo_available++;if(this.working=='REDO'){this.undo_names.push(this.current_action[0]);}else{this.clearRedoQueue();this.undo_names.push(name);}
this.settings.undoChange();}}
return this;};UndoManager.prototype.undo=function(){if(this.undo_queue.length>0){var id=this.undo_queue.pop();this.undo_available--;this.undo_names.pop();var action=this.action_index[id];delete this.action_index[id];this.working='UNDO';this.current_action=action;this.startGroup(action[0]);action[1].apply(action[3],action[2]);this.endGroup();delete this.current_action;this.working='';this.settings.undoChange();}
return this;};UndoManager.prototype.clearUndoQueue=function(){for(var i=this.undo_queue.length-1;i>=0;i--){delete this.action_index[this.undo_queue[i]];}
this.undo_queue=[];this.undo_available=0;this.redo_names=[];this.settings.undoChange();return this;};UndoManager.prototype.clearQueues=function(){this.action_index={};this.undo_queue=[];this.undo_available=0;this.undo_names=[];this.redo_queue=[];this.redo_available=0;this.redo_names=[];this.settings.undoChange();this.settings.redoChange();return this;};UndoManager.prototype.redo=function(){if(this.redo_queue.length>0){var id=this.redo_queue.pop();this.redo_available--;this.redo_names.pop();var action=this.action_index[id];delete this.action_index[id];this.working='REDO';this.current_action=action;this.startGroup(action[0]);action[1].apply(action[3],action[2]);this.endGroup();delete this.current_action;this.working='';this.settings.redoChange();}
return this;};UndoManager.prototype.clearRedoQueue=function(){for(var i=this.redo_queue.length-1;i>=0;i--){delete this.action_index[this.redo_queue[i]];}
this.redo_queue=[];this.redo_available=0;this.redo_names=[];this.settings.redoChange();return this;};UndoManager.prototype.startGroup=function(name){if(this.group!==null){this.group_queue.push(this.group);}
this.group_id=this.next_id++;this.group=[name,this.groupRunner,[[]],this,this.group_id];return this.group_id;};UndoManager.prototype.endGroup=function(){var grp=this.group;if(this.group_queue.length>0){this.group=this.group_queue.pop();}else{this.group=null;}
this.undoable.apply(this,grp);return this;};UndoManager.prototype.exitGroup=function(rollback){if(rollback!==false){var grp=this.group;this.startGroup('rolling back');grp[1].apply(grp[3],grp[2]);this.exitGroup(false);}
if(this.group_queue.length>0){this.group=this.group_queue.pop();}else{this.group=null;}
return this;};UndoManager.prototype.resumeGroup=function(id){if(this.group!==null){this.group_queue.push(this.group);}
this.group=this.action_index[id];this.group[5]=true;this.group_id=id;return this;};window.UndoManager=UndoManager;})();